### ISSUE TITLE
HTTP Error 500: Failed to exec CGI

### ISSUE THREAD

**Issue by TheNotOnly** [DonMcCoy/zpushOnZimbra#1]
I have everything set up as per your blog post, for some reasons, i'm not thrown an auth window when trying to load the xml in browser. Connectivity tool fails as well as Outlook autodiscover test.

Below is an extract of the logs:
`24/07/2021 18:15:03 [31515] [FATAL] [#unknown] Exception: (AuthenticationRequiredException) - Unauthorized
24/07/2021 18:15:03 [31515] [ERROR] [#unknown] Unable to complete autodiscover incorrect request: 'Unauthorized'
24/07/2021 18:15:04 [31526] [ INFO] [#unknown] Z-Push version='release/2.5-2.5.2.beta1'
24/07/2021 18:15:04 [31526] [ INFO] [#unknown] AuthenticationRequiredException: Unauthorized - code: 0 - file: /opt/z-push/src/autodiscover/autodiscover.php:149
24/07/2021 18:15:04 [31526] [FATAL] [#unknown] Exception: (AuthenticationRequiredException) - Unauthorized
24/07/2021 18:15:04 [31526] [ERROR] [#unknown] Unable to complete autodiscover incorrect request: 'Unauthorized'
24/07/2021 18:15:04 [31534] [ INFO] [#unknown] Z-Push version='release/2.5-2.5.2.beta1'
24/07/2021 18:15:04 [31534] [FATAL] [#unknown] FatalException: Request for a responseschema that is not supported (only mobilesync is supported): http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a - code: 0 - file: /opt/z-push/src/autodiscover/autodiscover.php:177
24/07/2021 18:15:04 [31534] [FATAL] [#unknown] Exception: (FatalException) - Request for a responseschema that is not supported (only mobilesync is supported): http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a
24/07/2021 18:15:04 [31534] [ERROR] [#unknown] Unable to complete autodiscover because of ZPushException. Error: Request for a responseschema that is not supported (only mobilesync is supported): http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a
24/07/2021 18:15:41 [31992] [ INFO] [#unknown] Z-Push version='release/2.5-2.5.2.beta1'
24/07/2021 18:15:41 [31992] [ INFO] [#unknown] AuthenticationRequiredException: Unauthorized - code: 0 - file: /opt/z-push/src/autodiscover/autodiscover.php:149
24/07/2021 18:15:41 [31992] [FATAL] [#unknown] Exception: (AuthenticationRequiredException) - Unauthorized
24/07/2021 18:15:41 [31992] [ERROR] [#unknown] Unable to complete autodiscover incorrect request: 'Unauthorized'
24/07/2021 18:15:41 [32000] [ INFO] [#unknown] Z-Push version='release/2.5-2.5.2.beta1'
24/07/2021 18:15:41 [32000] [ INFO] [#unknown] AuthenticationRequiredException: Unauthorized - code: 0 - file: /opt/z-push/src/autodiscover/autodiscover.php:149
24/07/2021 18:15:41 [32000] [FATAL] [#unknown] Exception: (AuthenticationRequiredException) - Unauthorized
24/07/2021 18:15:41 [32000] [ERROR] [#unknown] Unable to complete autodiscover incorrect request: 'Unauthorized'
24/07/2021 18:15:42 [32008] [ INFO] [#unknown] Z-Push version='release/2.5-2.5.2.beta1'
24/07/2021 18:15:42 [32008] [FATAL] [#unknown] FatalException: Request for a responseschema that is not supported (only mobilesync is supported): http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a - code: 0 - file: /opt/z-push/src/autodiscover/autodiscover.php:177
24/07/2021 18:15:42 [32008] [FATAL] [#unknown] Exception: (FatalException) - Request for a responseschema that is not supported (only mobilesync is supported): http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a
24/07/2021 18:15:42 [32008] [ERROR] [#unknown] Unable to complete autodiscover because of ZPushException. Error: Request for a responseschema that is not supported (only mobilesync is supported): http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a
`

**Comment by DonSYS91** [comment]
I stopped working with Zimbra so I won't be able to recall the project quickly. Sorry.

**Comment by DonSYS91** [comment]
I can however help if you're still facing the problem but you need to provide more info, where and when did you get that issue

**Comment by TheNotOnly** [comment]
Hello,

Thank you for getting back to me. Don't worry about it. I don't need
autodiscover anymore. But I am grateful for getting a reply from you.

Have a nice day ahead,
Darren Ramen
